import { Page } from '@playwright/test';
export declare function launchBrowser(): Promise<Page>;
export declare function navigateTo(page: Page, url: string): Promise<void>;
export declare function clickElement(page: Page, locator: string): Promise<void>;
export declare function enterText(page: Page, locator: string, text: string): Promise<void>;
export declare function clearText(page: Page, locator: string): Promise<void>;
export declare function pressKey(page: Page, locator: string, key: string): Promise<void>;
export declare function selectByLabel(page: Page, locator: string, value: string): Promise<void>;
export declare function checkBox(page: Page, locator: string): Promise<void>;
export declare function selectRadio(page: Page, locator: string): Promise<void>;
export declare function getText(page: Page, locator: string): Promise<string>;
export declare function getInputValue(page: Page, locator: string): Promise<string>;
export declare function waitForVisible(page: Page, locator: string): Promise<void>;
export declare function waitForPage(page: Page): Promise<void>;
export declare function takeScreenshot(page: Page, name: string): Promise<void>;
export declare function hover(page: Page, locator: string): Promise<void>;
export declare function rightClick(page: Page, locator: string): Promise<void>;
export declare function getTimeStamp(): number;
export declare function randomNumber(max: number): number;
//# sourceMappingURL=clsCommon.d.ts.map